# Generated by Django 4.0 on 2022-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_advocates_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
