# Generated by Django 4.0 on 2022-12-05 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_advocates_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocates',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
