# Generated by Django 4.0 on 2022-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_company_advocates_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='advocates',
            name='updated_time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
