# Generated by Django 4.0 on 2022-12-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_advocates_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocates',
            name='twitter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
