# Generated by Django 4.0 on 2022-12-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_advocates_twitter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advocates',
            new_name='Advocate',
        ),
    ]
