# Generated by Django 4.0 on 2022-12-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_advocates_advocate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
