# Generated by Django 4.0 on 2022-12-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_advocate_company_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='profile_banner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
